### ISSUE TITLE
Does not work on Windows gvim/neovim

### ISSUE THREAD

**Issue by aravind2612krishna** [jackguo380/vim-lsp-cxx-highlight#1]
According to the vim-lsp-cxx-highlight log
:
unescape_urlencode unescaped filename: /D:/**_<path_to_file>_**
notify_json_rpc error: buffer does not exist!atfunction <SNR>110_on_stdout[4]..<SNR>109_on_stdout[88]..<SNR>104_on_notification[20]..<SNR>111_notification_cb[1]..lsp_cxx_hl#notify_json_rpc[2]..<SNR>90_notify_json_rpc[51]..lsp_cxx_hl#notify_symbols[1]..<SNR>90_common_notify_checks, line 1

The message from ccls on windows:
{"response": {"method": "$ccls/publishSemanticHighlight", "jsonrpc": "2.0", "params": {"uri": "file:///D%3A/**_<path_to_file> ..._**.

Thank you for the plugin. It would be great if windows was supported as well by fixing this path problem. Hope the attached info helps.

**Comment by aravind2612krishna** [comment]
Please note the extra slash before the D: drive letter in above comment's vim-lsp-cxx-highlight log

**Comment by jackguo380** [comment]
Hi, thanks for trying out my plugin and reporting this.

I didn't realize it was allowed to have 3 /'s for URIs on windows so the conversion from URI to path was leaving the extra / in.

Try the latest commit and see if that fixes it.

**Comment by aravind2612krishna** [comment]
Hi, thanks for the quick fix. Now it at least seems to be trying to work. Still, however, the colors are off. The same symbol/word has half characters in different colors.
![image](https://user-images.githubusercontent.com/3424615/54622144-0ff4f000-4a8f-11e9-87ef-d7e934c847ea.png)
I can't give too much as I am testing this on proprietary code, but if I can help without giving away source info I will.
My gvim has +byte_offset and +timers. The same thing is reproducible in nvim-qt (gui frontend for neovim in Windows) as well.
Thanks again for showing interest in maintaining the Windows version as well.

**Comment by aravind2612krishna** [comment]
Hi, I tried setting lsRanges even though I have +byte_offset  and it fixes the issue and works!
So much faster than Chromatica of color_coded.

**Comment by jackguo380** [comment]
Ohh thats interesting, looks like something wrong with byte2line conversion on windows. If I had to guess its related to line endings being `\r\n` rather than `\n`. If it is line endings then ccls has a bug with its byte offset format (It uses `{'L': <offset of beginning>, 'R': <offset of end>}` instead of the LSP standard range).

Could you provide one of the `$ccls/publishSemanticHighlight` messages and the output of `:LspCxxHlDumpSyms` for that message with lsRanges disabled?

**Comment by aravind2612krishna** [comment]
A sample ccls highlight message has this: (the whole output is huge for my smallest file)
`{"id": 19121, "lsRanges": [], "storage": 0, "kind": 253, "ranges": [{"R": 12494, "L": 12487}, {"R": 12897, "L": 12890}, {"R": 12919, "L": 12912}, {"R": 16552, "L": 16545}, {"R": 16570, "L": 16563}], "parentKind": 6}`
Corresponding output of LspCxxHlDumpSyms doesn't have any numbers. Any option I need to set?
Debug Dump Symbols
```
0: parentKind = Method kind = Parameter storage = None
1: parentKind = Unknown kind = Method storage = None
2: parentKind = Unknown kind = Field storage = None
3: parentKind = Unknown kind = Method storage = None
...
```

**Comment by jackguo380** [comment]
Ah right I forgot that was removed from DumpSyms. If you could just find any symbol near the beginning of the file (On line 2+) and provide its range and the output of
`:echo lsp_cxx_hl#buffer#offsets2pos({"R": 12919, "L": 12912})` (Replace with your symbol's  range)
As well as where you expect the symbol should be (E.g. Line 2 Character 5)

Alternatively try converting your line endings to `\n` temporarily and see if that fixes highlighting.

**Comment by aravind2612krishna** [comment]
Line endings were CRLF. Converting line endings(dos2unix) does indeed fix it (works without lsranges).

**Comment by jackguo380** [comment]
Thanks for investigating. I just tried dos2unix and found it is infact ccls' problem. It looks like ccls is converting line endings and then forgetting about that when it sends the offsets for highlighting.

**Comment by jackguo380** [comment]
Closing this since enabling lsRanges fixes the issue.
