### ISSUE TITLE
Lsp client not found!

### ISSUE THREAD

**Issue by featheryus** [jackguo380/vim-lsp-cxx-highlight#10]
It doesn't work because "Lsp client not found!"
But coc did work already with ccls in my env.

Thanks.

**Comment by jackguo380** [comment]
Hi, can you enable some debugging:

Add the following lines to your `vimrc`
```vim
let g:lsp_cxx_hl_log_file = '/tmp/lsp-cxx-hl.log`
let g:lsp_cxx_hl_verbose_log = 1
```
Then reopen vim and post the contents of `/tmp/lsp-cxx-hl.log`.

**Comment by featheryus** [comment]
It works after I update coc.
Thanks.

**Comment by featheryus** [comment]
BTW, how can I change the color of member variable. It seems like high light white.
Thanks

**Comment by jackguo380** [comment]
In [syntax/lsp_cxx_highlight.vim#28](https://github.com/jackguo380/vim-lsp-cxx-highlight/blob/master/syntax/lsp_cxx_highlight.vim#L28) it is defined to White.

You can override it by defining the highlight group in your vimrc.
```vim
" Change member variables to Magenta
hi LspCxxHlGroupMemberVariable ctermfg=Magenta guifg=Magenta
```
