### ISSUE TITLE
Coloring artifacts in neovim - end of words are miscolored

### ISSUE THREAD

**Issue by dsirov** [jackguo380/vim-lsp-cxx-highlight#15]
**The Problem**
There are coloring artifacts (miscoloring at the end of words), see the attached pic.:
![image](https://user-images.githubusercontent.com/25965216/68997858-cb3a8680-08b3-11ea-9c28-d39982aba7eb.png)

**Offending Commit**
I have tracked down the offending commit, it is: [Add support for neovim text properties](https://github.com/jackguo380/vim-lsp-cxx-highlight/commit/58ed54cb3353a89afca3ca7517ed8b21546ecef8)

**Reproducing**
`:e tst.c`

With `tst.c` being:
```
int testfunc()
{
    return 0;
}

int main()
{
    testfunc();
}
```

**Expected Behavior**
When going back one commit (to [Better healing of values, log textprop failures](https://github.com/jackguo380/vim-lsp-cxx-highlight/commit/1bc406de30fbcaaa64aa6b681cb38b3682c1fd60)), everything looks OK:
![image](https://user-images.githubusercontent.com/25965216/68997853-c1188800-08b3-11ea-921c-c573435f9849.png)

**Configuration**
***Neovim***
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-pro
totypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovi
m/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim
/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-27b22526-64a7-4e92-9f8e-1f0b8288a453

Features: +acl +iconv +tui

***CoC.nvim - LSP Client***
tag: v0.0.74

**Log File:**
Logging was enabled by adding these lines:
```vim
let g:lsp_cxx_hl_log_file = '/tmp/lsp-cxx-hl.log'
let g:lsp_cxx_hl_verbose_log = 1
```
The log:
```vim
Sat 16 Nov 2019 08:53:30 PM IST: lsp_cxx_hl beginning initialization...
Sat 16 Nov 2019 08:53:30 PM IST: vim-lsp not detected
Sat 16 Nov 2019 08:53:30 PM IST: LanguageClient-neovim not detected
Sat 16 Nov 2019 08:53:30 PM IST: coc.nvim successfully registered
Sat 16 Nov 2019 08:53:30 PM IST: ccls regions:{'uri': 'file:///home/david/dev/vim/tst.c', 'skippedRanges': []}
Sat 16 Nov 2019 08:53:30 PM IST: textprop nvim notify skipped regions for tst.c
Sat 16 Nov 2019 08:53:30 PM IST: operation notify_skipped tst.c took   0.001006s to complete
Sat 16 Nov 2019 08:53:30 PM IST: ccls hl:{'uri': 'file:///home/david/dev/vim/tst.c', 'symbols': [{'id': 39, 'lsRanges': [], 'storage': 0, 'kind': 12, 'ranges': [{'R': 42, 'L': 38}], 'parentKind': 0}, {'id': 40, 'lsRanges': [], 'storage': 0, 'kind': 12, 'ranges': [{'R': 12, 'L': 4}, {'R': 59, 'L': 51}], 'parentKind': 0}]}
Sat 16 Nov 2019 08:53:30 PM IST: textprop nvim notify symbols for tst.c
Sat 16 Nov 2019 08:53:30 PM IST: operation notify_symbols tst.c took   0.001837s to complete
Sat 16 Nov 2019 08:53:30 PM IST: hl_skipped (textprop nvim) highlighted 0 skipped preprocessor regions in file tst.c
Sat 16 Nov 2019 08:53:30 PM IST: operation hl_skipped (textprop nvim) tst.c took   0.000181s to complete
Sat 16 Nov 2019 08:53:30 PM IST: hl_symbols (textprop nvim) highlighted 2 symbols in file tst.c
Sat 16 Nov 2019 08:53:30 PM IST: operation hl_symbols (textprop nvim) tst.c took   0.001821s to complete
Sat 16 Nov 2019 08:53:31 PM IST: ccls hl:{'uri': 'file:///home/david/dev/vim/tst.c', 'symbols': [{'id': 39, 'lsRanges': [], 'storage': 0, 'kind': 12, 'ranges': [{'R': 42, 'L': 38}], 'parentKind': 0}, {'id': 40, 'lsRanges': [], 'storage': 0, 'kind': 12, 'ranges': [{'R': 12, 'L': 4}, {'R': 59, 'L': 51}], 'parentKind': 0}]}
Sat 16 Nov 2019 08:53:31 PM IST: textprop nvim notify symbols for tst.c
Sat 16 Nov 2019 08:53:31 PM IST: operation notify_symbols tst.c took   0.000500s to complete
Sat 16 Nov 2019 08:53:31 PM IST: hl_symbols (textprop nvim) highlighted 2 symbols in file tst.c
Sat 16 Nov 2019 08:53:31 PM IST: operation hl_symbols (textprop nvim) tst.c took   0.000797s to complete
```

**Comment by jackguo380** [comment]
From the logs it looks like you don't have `lsRanges` enabled for `ccls`, see my recommended [coc-settings.json](https://github.com/jackguo380/vim-lsp-cxx-highlight/blob/35a4f2ff365f762948e3ea769a527616584acfeb/sample-configs/coc-settings.json#L11). I confirmed that I see the same problem as you with the option disabled, turning it on fixes it.

I'm going to stop putting `lsRanges` as a "recommendation" since it is too buggy, especially with the way some clients handle whitespace.

**Comment by dsirov** [comment]
You are right! I thought I did have `lsRanges` enabled, but apparently I have misplaced the construct inside the `coc-settings.json` file and it did not have any effect (of course).

Thanks for the fast reply!
