### ISSUE TITLE
Catching of E411

### ISSUE THREAD

**Issue by hlbstd** [jackguo380/vim-lsp-cxx-highlight#2]
On my localized system the string displayed by exceptions is different from the hard coded one in hl_helpers.vim:16
` catch /E411: highlight group not found:/`
This leads to many uncaught exception when opening any cpp file. 
Modifying the line to keep only the error code :
` catch /E411/`
Corrects this behavior.

**Comment by jackguo380** [comment]
Hi hlbstd, thanks for reporting this. This looks like a reasonable change, hopefully this latest commit fixes this for you.

**Comment by hlbstd** [comment]
Thanks, this should fix it except that I'm currently on the LanguageClient-Neovim branch. Should I switch to master instead (I'm using LanguageClient-Neovim obviously)?

**Comment by jackguo380** [comment]
I already merged that branch into master but I haven't had the time to test it yet. Any feedback would be appreciated as well.

**Comment by hlbstd** [comment]
Thank your for your clarification. The plugin now works as expected.
Integration with LanguageClient-Neovim seems to cause no issue for now.
Thank you as well for making this plugin, this is the best attempt at c/c++ syntax colouring I've seen yet. I will probably open more issues in the days to come as I'm very interested in the results.

**Comment by jackguo380** [comment]
Thanks for all the feedback, I'm glad the LanguageClient-neovim support is working well. Going to close this issue since it has been resolved.
