### ISSUE TITLE
LanguageClient-neovim + clangd support

### ISSUE THREAD

**Issue by theimpostor** [jackguo380/vim-lsp-cxx-highlight#23]
With https://github.com/autozimu/LanguageClient-neovim/pull/954 now merged, what remains for LanguageClient-neovim + clangd support? Using neovim and this plugin, highlighting doesn't appear to work out of the box. Is there more configuration required?

Thanks for the awesome plugin.

**Comment by jackguo380** [comment]
Hi, support for clangd (and other servers supported the proposed standard) is done entirely in LanguageClient-neovim, you don't need vim-lsp-cxx-highlight.

I realized I forgot to update the documentation for LanguageClient-neovim after autozimu/LanguageClient-neovim#954 got merged. But for reference I currently have the following configuration for clangd semantic highlighting:

```vim
let g:LanguageClient_semanticHighlightMaps['cpp'] = {
            \ 'entity.name.namespace.cpp': 'CppNameSpace',
            \ 'variable.other.field.cpp': 'CppMemberVariable',
            \ 'variable.other.enummember.cpp': 'EnumConstant',
            \ 'entity.name.function..*.cpp': 'Function',
            \ 'entity.name.type..*.cpp': 'Type',
            \ }

hi! CppNamespace ctermfg=Yellow guifg=#BBBB00 cterm=none gui=none
hi! CppMemberVariable ctermfg=White guifg=White
```
This is a fairly minimal configuration but should provide similar highlighting to what vim-lsp-cxx-highlight provides currently. Also note that clangd 10 and 11 provide more scopes such as ones for preprocessor (macros and skipped regions) which aren't in this configuration.

**Comment by theimpostor** [comment]
OK that's great to hear, and thanks for the sample configs. I will close this issue.
