### ISSUE TITLE
Enable syntax highlighting for cuda files

### ISSUE THREAD

**Issue by AlexAUT** [jackguo380/vim-lsp-cxx-highlight#36]
At least clangd and ccls support cuda files so it would be nice if this plugin also works with cuda files (.cu, .cuh).

When changing the filetype of a cuda file ```:set filetype=cpp``` it already provides correct highlighting, so it should already work correctly when enabled for the cuda filetype.

**Comment by jackguo380** [comment]
Thanks for the fix!
