### ISSUE TITLE
How to silent errors

### ISSUE THREAD

**Issue by aganm** [jackguo380/vim-lsp-cxx-highlight#44]
When I use the plugin, there's error logs that pop up at the bottom of my vim window 

![image](https://user-images.githubusercontent.com/20380758/94217268-9cb41180-feaf-11ea-9950-1adf80ed29a1.png)

But the highlighting still works just fine.

How do I silent those errors completely?

**Comment by jackguo380** [comment]
Hi, could you provide the code which produces these errors?

Errors propagating to the user indicates a bug which needs to be fixed, there isn't a way to just silence them.

**Comment by aganm** [comment]
Hmmm, I don't have these errors anymore and I don't remember if I did anything to fix it (I might just have updated my plugins).

If I get these again, I will reopen.
