### ISSUE TITLE
Semantic Highlighting toggles

### ISSUE THREAD

**Issue by d-karl** [jackguo380/vim-lsp-cxx-highlight#5]
I am experimenting with this plugin, and I find it pretty useful. I was wondering if there is a way I can toggle the semantic highlighting on/off, either globally or even per buffer?

**Comment by jackguo380** [comment]
Hi d-karl,

Thanks for trying out vim-lsp-cxx-highlight. I assume you are asking about this since `g:lsp_cxx_hl_ft_whitelist` is not specific enough.
I added a new command `:LspCxxHighlightDisable` which disables the highlighting on a per buffer basis. It can be re-enabled by using `:LspCxxHighlight`. Hopefully this is what you're looking for.

**Comment by d-karl** [comment]
Just tried it and it works great, many thanks!

Specifically, I was having a problem with too many disabled regions/editing in disabled regions and was looking for a way to get default highlighting back in a specific buffer.

Using this plugin + vim-lsp is my new favorite setup for sure!

**Comment by jackguo380** [comment]
Great to hear!

Just out of curiosity what issues were you having with editing in disabled regions? Was it performance related?

**Comment by d-karl** [comment]
I have taken over a legacy file, to clean it up, that has huge and numerous preprocessor blocks. Due to the file not being mentioned in my compile_commands.json all of them disabled in terms of what my language-server (ccls) is concerned with. 

Performance was disastrous, changing likes (j/k) took noticable amounts of time, and everything was syntax highlighted as comments. So I was looking for a way to disable the highlighting, to be able to at least edit inside those regions with default syntax highlighting.

**Comment by jackguo380** [comment]
I see, I have noticed some slowdowns for large files as well. Still working on supporting the new textprops feature in the newest vim, maybe that will provide better performance.
Going to close the issue since its solved. Thanks.
