### ISSUE TITLE
Error happened when using coc.nvim and ccls

### ISSUE THREAD

**Issue by stark-zhang** [jackguo380/vim-lsp-cxx-highlight#50]
As the picture said.

<img width="1278" alt="批注 2020-12-24 160632" src="https://user-images.githubusercontent.com/17326718/103073211-351e7700-4602-11eb-86d0-56f05f096b41.png">

in Vim 8.2.2202 and the newest version of ccls and coc.nvim

**Comment by WillDawnlll** [comment]
dude i got a same error recently . fixed it by  `let g:lsp_cxx_hl_use_text_props = 0`, this default enable in 8.2

**Comment by WillDawnlll** [comment]
and my vim version is 8.2.2425,  if you find some solution pls leave some info....thkx

**Comment by stark-zhang** [comment]
> dude i got a same error recently . fixed it by `let g:lsp_cxx_hl_use_text_props = 0`, this default enable in 8.2

thanks dude, but I had transferred to neovim, welcome to try my configuration in pure lua: [nvim config](https://github.com/stark-zhang/dotfiles-on-unix-like/tree/master/nvim)
