### ISSUE TITLE
Incompatible with neovim since PR13945

### ISSUE THREAD

**Issue by TrueJournals** [jackguo380/vim-lsp-cxx-highlight#53]
**Describe the bug**
When starting a version of neovim with a verison that includes https://github.com/neovim/neovim/pull/13945 the error "vim-lsp-cxx-highlight cannot find a LSP client" appears.  That PR changed "callbacks" to "handlers" inside `vim.lsp`

**To Reproduce**
Run trunk neovim with the plugin installed

**Expected behavior**
No error.

**Screenshots**

**Configuration (Fill this out):**
 - Vim or Neovim + Version: NVIM v0.5.0-dev+1115-gc1fbc2ddf
 - Which Lsp Client is being used and Lsp Client Version: Built-in LSP client

**Log File:**
```vim
Sun 28 Feb 2021 09:03:57 AM CST: lsp_cxx_hl beginning initialization...
Sun 28 Feb 2021 09:03:57 AM CST: vim-lsp not detected
Sun 28 Feb 2021 09:03:57 AM CST: LanguageClient-neovim not detected
Sun 28 Feb 2021 09:03:57 AM CST: coc.nvim not detected
Sun 28 Feb 2021 09:03:57 AM CST: nvim-lsp failed to register: Vim(lua):E5108: Error executing lua [string ":lua"]:3: attempt to index field 'callbacks' (a nil value)
Sun 28 Feb 2021 09:03:57 AM CST: Failed to find a compatible LSP client
```

**Comment by csaez** [comment]
Thanks for reporting this, I found the same issue after updating my setup today :)
Renaming the calls to `callbacks` as `handlers`, as @TrueJournals mentioned, seems to fix the issue for me.

i.e.
https://github.com/jackguo380/vim-lsp-cxx-highlight/blob/7c47d39d808118f0ef030b15db28ff3995d91cb6/autoload/lsp_cxx_hl/client/nvim_lsp.vim#L18-L32
