### ISSUE TITLE
Semantic highlighting only works when starting Neovim with file argument

### ISSUE THREAD

**Issue by cdelledonne** [jackguo380/vim-lsp-cxx-highlight#6]
### Bug description

As from the title, semantic highlighting only works when starting Neovim **with** a file argument, e.g.:
```
$ nvim main.c
```

I'm using [ccls][ccls] as language server and [LanguageClient-neovim][langclient] (LC) as client.

I ended up posting an issue here because, from what I could infer from some debugging, language server and client seem to work. Specifically, I see that ccls publishes semantic highlight (`$ccls/publishSemanticHighlight`) and LC receives those messages.

When starting Neovim **without** a file argument, and then opening a C file, the log from LC suggests that the `$ccls/publishSemanticHighlight` are received but not handled:
```
16:55:11 WARN unnamed src/rpchandler.rs:186 Message not handled: Notification { jsonrpc: Some(V2), method: "$ccls/publishSemanticHighlight", params: ... }
```
In that case, vim-lsp-cxx-highlight's log is also missing the lines
```
Fri 10 May 2019 04:36:34 PM CEST: ccls hl:{ ... }
```
that indicate handling of semantic highlighting information from ccls.

### To reproduce

```bash
$ cd /tmp
$ mkdir hltest
$ cd hltest
$ touch test.c
$ nvim # no file argument
```

Then, `:e test.c` and insert the following
```c
int main() {}
```
Save, and check that semantic highlighting does not work (at least in my case), that is, the symbol `main` is not highlighted.

### Environment

* Neovim
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Features: +acl +iconv +jemalloc +tui
```
* Ubuntu 18.04.2 LTS
* Language server: ccls
* Language client: LanguageClient-neovim

### Minimal .vimrc/init.vim configuration

```vim
call plug#begin('~/.local/share/nvim/plug')
Plug 'autozimu/LanguageClient-neovim', { 'branch': 'next', 'do': 'bash install.sh' }
Plug 'jackguo380/vim-lsp-cxx-highlight'
call plug#end()

let g:LanguageClient_serverCommands = {
    \ 'c': ['ccls']
    \ }
```

Using vim-plug as plugin manager.

[ccls]: https://github.com/MaskRay/ccls
[langclient]: https://github.com/autozimu/LanguageClient-neovim

**Comment by jackguo380** [comment]
Hi cdelledonne, thanks for the super detailed bug report, it was really helpful. As it turns out LanguageClient-neovim does not initialize until a file is opened, but vim-lsp-cxx-highlight initializes on vim/nvim startup the registration with LC fails.

It also turns out that preprocessor skipped regions were broken for LC, so thats fixed as well.

Let me know if this fixes your issue!

**Comment by cdelledonne** [comment]
Wow @jackguo380 that was responsive, thanks! Your latest changes seem to have fixed the issue, thus I'm closing this.

I really hope that one day all the language-client-related features will be merged into one plugin, as that would avoid twisted cross-debugging and render the whole experience better. I'm sure we'll get there. That said, thanks a lot for your efforts!
