### ISSUE TITLE
highlight not working in alpine container

### ISSUE THREAD

**Issue by Leo843** [jackguo380/vim-lsp-cxx-highlight#68]
**Describe the bug**
I setup a container as a portable development environment, but there is no syntax highlight in cpp files.

**To Reproduce**
Here is a simplified version of the Dockerfile.
```
FROM alpine

# common tools
RUN true \
  && apk update \
  && apk add bash \
  && apk add curl \
  && apk add cmake \
  && apk add git \
  && apk add clang \
  && apk add g++ \
  && apk add clang-extra-tools \
  && rm -rf /var/cache/apk/*

# vim
RUN true \
  && apk update \
  && apk add python3 \
  && apk add nodejs \
  && apk add npm \
  && apk add vim \
  && rm -rf /var/cache/apk/*

# create user
ARG USER_NAME=leo
RUN adduser --disabled-password --gecos '' $USER_NAME

# change user
WORKDIR /home/${USER_NAME}
USER ${USER_NAME}
ENV USER=${USER_NAME} HOME=/home/${USER_NAME}

# vim configuration
RUN true \
  && curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim \
  && echo "set nocompatible" >> .vimrc \
  && echo "call plug#begin()" >> .vimrc \
  && echo "Plug 'neoclide/coc.nvim', {'branch': 'release'}" >> .vimrc \
  && echo "Plug 'jackguo380/vim-lsp-cxx-highlight'" >> .vimrc \
  && echo "call plug#end()" >> .vimrc \
  && echo "let g:lsp_cxx_hl_verbose_log = 1" >> .vimrc \
  && echo "let g:lsp_cxx_hl_log_file = '/tmp/vim-lsp-cxx-hl.log'" >> .vimrc \
  && vim +PlugInstall +qa

# install coc-clangd
RUN true \
  && mkdir -p .config/coc/extensions \
  && cd .config/coc/extensions \
  && echo '{"dependencies":{}}' >> package.json \
  && npm install coc-clangd --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod \
  && cd ${HOME}

# sample/main.cpp
RUN true \
  && mkdir sample \
  && echo "#include <cstdio>" >> sample/main.cpp \
  && echo "" >> sample/main.cpp \
  && echo "int main(int argc, char** argv){" >> sample/main.cpp \
  && echo "  puts(\"Hello World\");" >> sample/main.cpp \
  && echo "}" >> sample/main.cpp

# sample/.vim/coc-settings.json
RUN true \
  && mkdir sample/.vim \
  && echo "{" >> sample/.vim/coc-settings.json \
  && echo '  "clangd.semanticHighlighting": true' >> sample/.vim/coc-settings.json \
  && echo "}" >> sample/.vim/coc-settings.json

CMD ["/bin/bash"]
```

When `sample/main.cpp` is opened with vim in the running container, no highlight appears.

**Expected behavior**
I expect symbols `main` and `puts` to be highlighted (function names are highlighted by default).

**Screenshots**
From the container
![Screenshot from 2021-07-02 14-09-51](https://user-images.githubusercontent.com/55994057/124272567-32678600-db3f-11eb-88f8-240bf0ed2fe7.png)
From the host (expected behavior)
![Screenshot from 2021-07-02 14-19-42](https://user-images.githubusercontent.com/55994057/124273952-f2090780-db40-11eb-8d01-f6bfd1c5a9f7.png)

**Configuration (Fill this out):**
 - Output of `vim --version`
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 07 2021 22:45:17)
Included patches: 1-2956
Compiled by Alpine Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            -gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               -ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vim/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -Os -fomit-frame-pointer -Os -fomit-frame-pointer -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lm -lncurses -L/usr/lua5.3/lib -llua 

```
 - I am using clangd with coc.nvim and coc-clangd (see Dockerfile)
 - Content of the `.vimrc`  (see Dockerfile)
```
set nocompatible
call plug#begin()
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'jackguo380/vim-lsp-cxx-highlight'
call plug#end()
let g:lsp_cxx_hl_verbose_log = 1
let g:lsp_cxx_hl_log_file = '/tmp/vim-lsp-cxx-hl.log'
```

**Log File:**
- Here is the output of `:LspCxxHlDumpSyms`.

```
Debug Dump Symbols
End of Debug Dump Symbols
```
- Here is the content of the log file.
```
Fri Jul  2 12:02:28 2021: lsp_cxx_hl beginning initialization...
Fri Jul  2 12:02:28 2021: vim-lsp not detected
Fri Jul  2 12:02:28 2021: LanguageClient-neovim not detected
Fri Jul  2 12:02:28 2021: coc.nvim successfully registered
Fri Jul  2 12:02:28 2021: Not registering nvim-lsp as this is not Neovim
Fri Jul  2 12:05:30 2021: lsp_cxx_hl beginning initialization...
Fri Jul  2 12:05:30 2021: vim-lsp not detected
Fri Jul  2 12:05:30 2021: LanguageClient-neovim not detected
Fri Jul  2 12:05:30 2021: coc.nvim successfully registered
Fri Jul  2 12:05:30 2021: Not registering nvim-lsp as this is not Neovim
Fri Jul  2 12:05:33 2021: operation hl_skipped (textprop) sample/main.cpp took   0.000117s to complete
Fri Jul  2 12:05:33 2021: operation hl_symbols (textprop) sample/main.cpp took   0.000137s to complete
```

**Additional context**
none atm

**Comment by unphased** [comment]
I'm experiencing something similar to this but with not nearly as minimal a configuration. It only started happening this week for me, and what's curious is that I hadn't explicitly run PlugUpdate before it broke. Something weird is going on. It's not some change from this repo since it has been unchanged since April. 

Currently am scrounging for additional debugging output from the related tools, because 
```
let g:lsp_cxx_hl_log_file = '/tmp/vim-lsp-cxx-hl.log'
let g:lsp_cxx_hl_verbose_log = 1
```
is not providing any useful output for me. Is that the case for you as well?

**Comment by unphased** [comment]
OK as has been noted elsewhere, https://github.com/clangd/coc-clangd/issues/287 contains a temporary fix. This fix is to revert coc.nvim to version 0.0.80 (I just went into plugged/ and checked that commit out, and I got my highlights back). 

It seems like there is some general disarray around coc and clangd interoperation for semantic highlighting features being added. It seems like whatever lsp-cxx-highlight is listening for isn't being delivered by clangd when clangd detects coc supporting the new semantic highlight feature. 

Luckily, for the time being, the workaround is to keep coc at the older release version for the time being and the previously working behavior continues. Hopefully soon we will get a better integrated system for this (which will work on all languages rather than using this plugin to get it just for C++).

**Comment by janwaltl** [comment]
Can confirm, highligting broke after `:PlugUpdate` for me, navigating to `~/.vim/plugged/coc.nvim` and doing `git checkout v0.0.80` fixed it for now.

**Comment by xspeed1989** [comment]
> git checkout v0.0.80

It doesn't works for me

**Comment by janwaltl** [comment]
I do not know what "doesn't work" means exactly.

**Comment by janwaltl** [comment]
> 
> 
> > git checkout v0.0.80
> 
> It doesn't works for me

I do not know what "doesn't work" mean.

**Comment by xspeed1989** [comment]
> > > git checkout v0.0.80
> > 
> > 
> > It doesn't works for me
> 
> I do not know what "doesn't work" mean.

highlight doesn't work after checkout to v0.0.80 too

**Comment by fannheyward** [comment]
Set `coc.preferences.semanticTokensHighlights` to `false` in your coc-settings.json to disable the new semanticTokens highlighting, to use the old semanticHighlighting protocol.

The reason: clangd 12 supports both the two highlighting protocol, the new semanticTokens and the old semanticHighlighting. coc-clangd used the old protocol with vim-lsp-cxx-highlight to do highlighting. coc added semanticTokens support in latest, clangd will force use the new protocol, some highlighting group maybe broken. You need to disable the new protocol by `coc.preferences.semanticTokensHighlights` to use the old one.

**Comment by Leo843** [comment]
The highlighting works after setting `coc.preferences.semanticTokensHighlights` to `false` in `coc-settings.json`.

```
{
  "clangd.semanticHighlighting": true,
  "coc.preferences.semanticTokensHighlights": false
}
```

**Comment by unphased** [comment]
Does anyone have an idea when the new approach to semantic highlighting can work for C++? What is the root cause of breakage that is leading us to have to pin our coc.nvim at 0.0.80? Although it is a working setup for now it feels very precarious.
