### ISSUE TITLE
Static functions do resolve to strageclass 'None'

### ISSUE THREAD

**Issue by izemmouri** [jackguo380/vim-lsp-cxx-highlight#7]
Hi,
The title says it all, and it's most likely a language server issue, but still, it seems that declaring things like: 
`static void foo() { return 0; }`
will not be recognized as a function with storageclass static!

**Comment by jackguo380** [comment]
Please provide more details, what language server are you using? what LSP client do you have?

I do see that static functions do not have the proper storage specifier using ccls but that is not vim-lsp-cxx-highlight's fault. Please confirm this bug using your example and file a issue over on ccls' issue tracker. (I have filed issues in the past if you want an example: Maskray/ccls#329)

vim-lsp-cxx-highlight has some builtin debug utilities that may help you, see: `:help vim-lsp-cxx-highlight-commands`. You may also want to enable verbose logging for both vim-lsp-cxx-highlight and your LSP client.
