### ISSUE TITLE
c  multi line in macro  "#ifdef #endif" , last line just previews few char has  comment color (gray)

### ISSUE THREAD

**Issue by WillDawnlll** [jackguo380/vim-lsp-cxx-highlight#72]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/28567110/131780048-c5a8869a-40aa-4011-8c54-9bb65c059d44.png)

**Configuration (Fill this out):**
 - Vim or Neovim + Version
 - Which Lsp Client is being used and Lsp Client Version
 - Parts of your `vimrc` or `init.vim` that you think are relevant to vim-lsp-cxx-highlight

**Log File:**
Enable logging by adding these lines:
```vim
let g:lsp_cxx_hl_log_file = '/tmp/lsp-cxx-hl.log'
let g:lsp_cxx_hl_verbose_log = 1
```
Then post the contents of the log file:

```vim
<Log File Contents>
```

**Additional context**

**Comment by jackguo380** [comment]
Please file out the bug report template fully. Your code example also needs to be more than a screenshot, I'm not going to re-type it from the image, that's a waste of time. 

Closing until this is done.
