### ISSUE TITLE
coc.nvim as an LSP client

### ISSUE THREAD

**Issue by dsirov** [jackguo380/vim-lsp-cxx-highlight#8]
Is it possible to support coc.nvim as another LSP client?

**Comment by jackguo380** [comment]
Hi dsirov,

It seems since the last time I looked into supporting it someone has filed a issue specifically for vim-lsp-cxx-highlight neoclide/coc.nvim#759 and I didn't notice it.

I just pushed support for coc.nvim, let me know if it works well for you.

**Comment by dsirov** [comment]
Thanks for such quick response.
Works great!
